
		<div style="padding:20px;">
        <h3>Recent Updates</h3>
                <p><b>[3/15/2007]</b> AutoPatch version 1.1 is nearly done. Lots of new features including help for horizontal database scaling strategies, as well as the beginning of .NET port</p>
		<p> <a href="http://www.joltawards.com/2007"><img src="images/JoltLogo2.gif" width="150" height="176" alt="Jolt Awards Logo"  border="0"/></a><br>
        <b>[01/19/2007]</b> AutoPatch is a finalist in the utilities category for the 2007 <a href="http://www.joltawards.com/2007">Jolt Awards!</a>   <b>w00t!</b> </p>
		<p><b>[01/04/2007]</b> We have released AutoPatch version 1.0! In use for years, it was time... <a href="https://sourceforge.net/project/showfiles.php?group_id=106637">Download It</a></p>
		 
		  
        </div><!--padding: 20-->
    </div><!--/left-->

    <div id="right"><br>
