
		<div style="padding:20px;">
        <h3>Recent Updates</h3>
        	<p><b>Announcing AutoPatch 1.2 Beta!</b> Including new functionality allowing you to rollback a patches. Be sure to <a href="http://sourceforge.net/projects/autopatch">download</a> it and check out the new features</p>
        <!--	
                <p><b>[11/1/2007]</b> AutoPatch version 1.1 is nearly done (we promise!). Tons of new features including help for horizontal database scaling strategies, as well as the beginning of .NET port. It's stable now, pull from CVS if you want.</p>
		<p> <a href="http://www.joltawards.com/2007"><img src="images/JoltLogo2.gif" width="150" height="176" alt="Jolt Awards Logo"  border="0"/></a><br>
        <b>[01/19/2007]</b> AutoPatch was a finalist in the utilities category for the 2007 <a href="http://www.joltawards.com/2007">Jolt Awards!</a>   <b>w00t!</b> </p>
		<p><b>[01/04/2007]</b> We have released AutoPatch version 1.0! In use for years, it was time... <a href="http://sourceforge.net/projects/autopatch">Download It</a></p>
		 -->
		  
        </div><!--padding: 20-->
    </div><!--/left-->

    <div id="right"><br>
